# Generated by Django 5.1 on 2024-09-04 04:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 9, 4, 1, 8, 13, 975727)),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=10000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('post_nexus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.postmodel')),
            ],
        ),
    ]
